CONST PATH = REQUIRE('PATH')

CONSOLE.LOG(PATH.RELATIVE('/DATA/ORANDEA/TEST/AAA', '/DATA/ORANDEA/IMPL/BBB'))
CONSOLE.LOG(PATH.RESOLVE('/FOO/BAR', './BAZ'))
CONSOLE.LOG(PATH.NORMALIZE('/FOO/BAR//BAZ/ASDF/QUUX/ ..'))
CONSOLE.LOG(PATH.NORMALIZE('C:\\TEMP\\\\FOO\\BAR\\ .. \\'))
CONSOLE.LOG(PATH.PARSE('/HOME/USER/DIR/FILE.TXT'))
CONSOLE.LOG(PATH.JOIN('/FOO', 'BAR', 'BAZ/ASDF', 'QUUX', '..'))
CONSOLE.LOG(PATH.SEP)